FROM centos:7

ENV ANSIBLE_HOST_KEY_CHECKING=False

# Install Ansible
RUN yum -y install epel-release
RUN yum -y install git ansible sudo
RUN yum clean all
RUN mkdir -p /ansible

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' /etc/sudoers

# Prepare role in the docker container
ONBUILD ARG ROLE_NAME

ONBUILD COPY inventory /ansible
ONBUILD COPY ../ /ansible/roles/${ROLE_NAME}
ONBUILD COPY ./test.yml /ansible

ONBUILD WORKDIR /ansible
ONBUILD ENTRYPOINT [ "ansible-playbook" ]
ONBUILD CMD [ "-i", "inventory", "test.yml" ]

ENTRYPOINT [ "ansible" ]
CMD [ "-v" ]
