---
# Role tasks

- block:
    - name: create environment variables file
      file:
        path: "{{ environment_file }}"
        owner: "{{ environment_file_owner }}"
        group: "{{ environment_file_group }}"
        mode: "{{ environment_file_mode }}"
        state: file
      register: environment_file_result

    - name: configure environment variables
      lineinfile:
        dest: "{{ environment_file }}"
        regexp: "^{{ environment_item.key }}="
        line: '{{ environment_item.key }}="{{ environment_item.value }}"'
      when: environment_item.value is not none
      loop: "{{ environment_config | dict2items }}"
      loop_control:
        loop_var: environment_item
        label: "{{ environment_item.key }}"
  tags:
    - role::environment
