# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# Disable repos mirror list
RUN sed -i -r "s%(^mirrorlist=.*)%#\1%g" /etc/yum.repos.d/{CentOS-Base.repo,CentOS-Debuginfo.repo,CentOS-fasttrack.repo}

# Point repos to vault
RUN sed -i -r "s%#baseurl=http://mirror.centos.org/%baseurl=http://vault.centos.org/%g" /etc/yum.repos.d/{CentOS-Base.repo,CentOS-Debuginfo.repo,CentOS-fasttrack.repo}

# Install base packages
RUN yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;
